server:
  port: 9000

logging:
  level:
    com:meraj: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: lombok
          group: comments
          content-type: application/json
        output:
          destination: lombok-chat
          group: comments-chat
          content-type: application/json
