server:
  port: 9001

logging:
  level:
    com:meraj: DEBUG

# http://localhost:9001/actuator/hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: lombok
        output:
          destination: lombok
          group: comments
          content-type: application/json


